# Generated by Django 5.0 on 2023-12-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.TextField()),
                ('introduction', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('body', models.TextField()),
                ('body1', models.TextField()),
                ('body2', models.TextField()),
                ('body3', models.TextField()),
                ('body4', models.TextField()),
                ('body5', models.TextField()),
                ('body6', models.TextField()),
                ('body7', models.TextField()),
                ('body8', models.TextField()),
                ('body9', models.TextField()),
                ('outro', models.TextField()),
            ],
        ),
    ]
