# Generated by Django 5.0 on 2023-12-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_body2_alter_post_body3_alter_post_body4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body10',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='outro1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
