# Generated by Django 5.0 on 2023-12-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_post_body10_post_outro1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='outro',
            new_name='posted_by',
        ),
        migrations.RemoveField(
            model_name='post',
            name='outro1',
        ),
        migrations.AddField(
            model_name='post',
            name='position',
            field=models.TextField(blank=True, null=True),
        ),
    ]
