# Generated by Django 4.2.9 on 2024-01-27 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_outro_post_posted_by_remove_post_outro1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_time']},
        ),
    ]
