# Generated by Django 4.2.9 on 2024-01-27 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_time']},
        ),
    ]
