# Generated by Django 4.1.3 on 2024-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.DecimalField(decimal_places=1, default=3.2, max_digits=10),
        ),
    ]
