# Generated by Django 4.1.3 on 2024-04-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_post_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hottest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.TextField()),
                ('introduction', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('views', models.DecimalField(decimal_places=1, default=3.2, max_digits=10)),
                ('body', models.TextField()),
                ('body1', models.TextField()),
                ('body2', models.TextField(blank=True, null=True)),
                ('body3', models.TextField(blank=True, null=True)),
                ('body4', models.TextField(blank=True, null=True)),
                ('body5', models.TextField(blank=True, null=True)),
                ('body6', models.TextField(blank=True, null=True)),
                ('body7', models.TextField(blank=True, null=True)),
                ('body8', models.TextField(blank=True, null=True)),
                ('body9', models.TextField(blank=True, null=True)),
                ('body10', models.TextField(blank=True, null=True)),
                ('posted_by', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
